# Generated by Django 3.2.3 on 2021-05-19 11:36

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        db_column="AVATAR",
                        null=True,
                        upload_to=accounts.models.upload_path,
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, db_column="BIO", null=True, verbose_name="Bio"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_column="",
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "is_mvp",
                    models.BooleanField(
                        default=False, verbose_name="Saler of the Month"
                    ),
                ),
                (
                    "registered",
                    models.DateTimeField(
                        auto_now_add=True, db_column="RGSTD", verbose_name="Registered"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        db_column="STATUS", default=True, verbose_name="Account Status"
                    ),
                ),
                (
                    "deactivated_date",
                    models.DateTimeField(
                        blank=True,
                        db_column="DDATE",
                        editable=False,
                        null=True,
                        verbose_name="Deactivaed",
                    ),
                ),
                (
                    "gender",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, "Male"), (2, "Famale")],
                        db_column="GENDER",
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        db_column="WHTSP",
                        max_length=50,
                        null=True,
                        verbose_name="Whatsapp Number",
                    ),
                ),
                (
                    "telgram",
                    models.CharField(
                        blank=True,
                        db_column="TLGRM",
                        max_length=50,
                        null=True,
                        verbose_name="Telegram Number",
                    ),
                ),
                (
                    "insta",
                    models.CharField(
                        blank=True,
                        db_column="INSTA",
                        max_length=30,
                        null=True,
                        verbose_name="Instagram Username",
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True,
                        db_column="TWTTR",
                        max_length=30,
                        null=True,
                        verbose_name="Twitter Username",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True,
                        db_column="FBOOK",
                        max_length=30,
                        null=True,
                        verbose_name="Facebook Username",
                    ),
                ),
                (
                    "realtor",
                    models.OneToOneField(
                        db_column="RLTR",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Realtor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "db_table": "PROFILE",
                "managed": True,
            },
        ),
    ]
