# Generated by Django 3.2.3 on 2021-05-19 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import estate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="Category Name")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "CTGRY",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Title")),
                ("house_id", models.PositiveIntegerField(verbose_name="House Id")),
                ("name", models.CharField(max_length=200, verbose_name="Title")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Phone Number")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                (
                    "contact_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Contact Date"
                    ),
                ),
                (
                    "user_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="User Id"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
                "db_table": "CONTACTS",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_column="TITLE", max_length=60, verbose_name="Title"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_column="ADDRESS",
                        max_length=60,
                        null=True,
                        verbose_name="Address",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        db_column="CITY",
                        max_length=60,
                        null=True,
                        verbose_name="City",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        db_column="STATE",
                        max_length=60,
                        null=True,
                        verbose_name="State",
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        blank=True,
                        db_column="ZIP",
                        max_length=20,
                        null=True,
                        verbose_name="Zip Code",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("TZS", "TZS")],
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0, verbose_name="Price")),
                (
                    "bedroom",
                    models.PositiveIntegerField(default=1, verbose_name="Bedrooms"),
                ),
                (
                    "bathroom",
                    models.PositiveIntegerField(default=0, verbose_name="Bathroom"),
                ),
                (
                    "garage",
                    models.PositiveIntegerField(default=0, verbose_name="Garage"),
                ),
                (
                    "square_feet",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Square Feet"
                    ),
                ),
                (
                    "lot_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Lot Size",
                    ),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="Paid")),
                ("update", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "property_type",
                    models.CharField(max_length=50, verbose_name="Propery Type"),
                ),
                (
                    "furnished",
                    models.BooleanField(default=False, verbose_name="Furnished"),
                ),
                (
                    "exchange_posibility",
                    models.BooleanField(
                        default=False, verbose_name="Exchange Possibilty"
                    ),
                ),
                (
                    "realtor_fee",
                    models.BooleanField(default=True, verbose_name="Realtor Fee"),
                ),
                (
                    "image1",
                    models.ImageField(
                        upload_to=estate.models.upload_path, verbose_name="Main Image"
                    ),
                ),
                (
                    "image2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=estate.models.upload_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "image3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=estate.models.upload_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "image4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=estate.models.upload_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "image5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=estate.models.upload_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "image6",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=estate.models.upload_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "image7",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=estate.models.upload_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Is Published"),
                ),
                (
                    "posted",
                    models.DateTimeField(auto_now_add=True, verbose_name="Posted"),
                ),
                (
                    "available_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Available"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estate.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "realtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="poster",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Realtor",
                    ),
                ),
            ],
            options={
                "verbose_name": "House",
                "verbose_name_plural": "Houses",
                "db_table": "HOUSE",
                "ordering": ["-pk", "-posted"],
                "managed": True,
            },
        ),
    ]
